#!/bin/bash
################################################################################
#
# File:         $RCSfile: Axcient,v $
# Revision:	$Revision: $
# Description:	Client specific start up for Axcient
# Author:       Andrew@DeFaria.com
# Created:	Tue Aug 13 11:49:46 PDT 2013
# Modified:     $Date: $
# Language:     bash
#
# (c) Copyright 2013, Andrew@DeFaria.com, all rights reserved.
#
################################################################################
function git () {
  # Need to reset title since we put the branch name in the titlebar
  git=$(which git)

  if [ "$1" = "checkout" ]; then
    $git $@
    set_title
  else
    $git $@
  fi
} # git
