#!/bin/bash
################################################################################
#
# File:         $RCSfile: cPanel,v $
# Revision:	$Revision: 1.0 $
# Description:	Client specific start up for cPanel
# Author:       Andrew@DeFaria.com
# Created:      Fri Nov  8 13:50:01 PST 2013
# Modified:     $Date: $
# Language:     bash
#
# (c) Copyright 2013, ClearSCM, Inc., all rights reserved.
#
################################################################################
prepend_to_path /usr/local/cpanel/build-tools
prepend_to_path /usr/local/cpanel/3rdparty/lib/path-bin
prepend_to_path /usr/local/cpanel/3rdparty/bin
prepend_to_path /usr/local/cpanel/bin
append_to_path /usr/local/sbin
append_to_path /usr/local/bin
append_to_path /usr/sbin
append_to_path /opt/cpanel/composer/bin
append_to_path /opt/cplint/bin
append_to_path /root/bin

# Useful aliases
alias makesb4='pushd $ulc; make -j4 sandbox; popd'
# Find code!
if [ -d ~/.vscode-server ]; then
  codePath=$(dirname $(find ~/.vscode-server/bin -name code))
  if [ -n "$codePath" ]; then
    append_to_path $codePath
  else
    echo "Warning - unable to find code"
  fi
fi

# Intended to be used for root
WIZARD="CPanel"

#export CDPATH=/usr/local
export ulc=/usr/local/cpanel
export ulp=/usr/local/cp-monitoring-cpanel-plugin
export ulw=/usr/local/cp-monitoring-whm-plugin
export ulb=/usr/local/cp-banners-plugin
export CPANEL_TEAM='release'
# NOTE: To trim down the amount of time for make sandbox, you may define
# the environment variable SANDBOX_LOCALES which is a space separated list
# of locales to build. You can add the following to your .bash_profile to
# only build English and Spanish.
#export SANDBOX_LOCALES=en

# EA Tools
export EATOOLS_BUILD_DIR=/usr/local/ea-tools/SOURCES/
export EATOOLS_BIN_DIR=/usr/local/ea-tools/SOURCES/
export OBS_USERNAME=A.defaria

#alias ulc="cd /usr/local/cpanel"
alias perl="$ulc/3rdparty/bin/perl"
alias stencilwatch='npx stencil test --spec --watchAll'
alias stencilwatche2e='npx stencil test --spec --e2e --watchAll'

# Unset PERLTIDY and PERLCRITIC as those variable override looking for
# ~/.perltidyrc and ~/.perlcriticrc.
unset PERLTIDY
unset PERLCRITIC

# This is a closer call to how cplint is called by merge_request
alias cplintm="cplint --branched-from=upstream/$(cat /usr/local/cpanel/.branched_from)"

# This is the completer function for ulc. This completes any path that comes
# after the ulc as a path completion relative to $ulc
function _ulc {
  local cur prev

  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  # to be continued
} # _ulc

function ulc {
  path=$1

  if [ -s "$1" ]; then
    cd $ulc/$path
  else
    cd $ulc
  fi
} # ulc

function ulp {
  path=$1

  if [ -s "$1" ]; then
    cd $ulp/$path
  else
    cd $ulp
  fi
} # ulp


function ulw {
  path=$1

  if [ -s "$1" ]; then
    cd $ulw/$path
  else
    cd $ulw
  fi
} # ulw

function ulb {
  path=$1

  if [ -s "$1" ]; then
    cd $ulb/$path
  else
    cd $ulb
  fi
} # ulb

