#!/bin/bash
################################################################################
#
# File:         $RCSfile: Audience,v $
# Revision:	$Revision: 1.0 $
# Description:	Client specific start up for Audience
# Author:       Andrew@ClearSCM.com
# Created:      Fri Nov  8 13:50:01 PST 2013
# Modified:     $Date: $
# Language:     bash
#
# (c) Copyright 2013, ClearSCM, Inc., all rights reserved.
#
################################################################################
prepend_to_path /usr/local/cpanel/build-tools
prepend_to_path /usr/local/cpanel/3rdparty/lib/path-bin
prepend_to_path /usr/local/cpanel/3rdparty/bin
append_to_path /usr/local/sbin
append_to_path /usr/local/bin
append_to_path /usr/sbin
append_to_path /opt/cpanel/composer/bin
append_to_path /opt/cplint/bin
append_to_path /root/bin

# Intended to be used for root
WIZARD="CPanel"

export CDPATH=/usr/local
export ulc=/usr/local/cpanel
export ulp=/usr/local/cp-monitoring-cpanel-plugin
export CPANEL_TEAM='scrum'

#alias ulc="cd /usr/local/cpanel"
alias cperl="$ulc/3rdparty/bin/perl"

# Unset PERLTIDY and PERLCRITIC as those variable override looking for
# ~/.perltidyrc and ~/.perlcriticrc.
unset PERLTIDY
unset PERLCRITIC

# This is the completer function for ulc. This completes any path that comes
# after the ulc as a path completion relative to $ulc
function _ulc {
  local cur prev

  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  # to be continued
} # _ulc

function ulc {
  path=$1

  if [ -s "$1" ]; then
    cd $ulc/$path
  else
    cd $ulc
  fi
} # ulc

function ulp {
  path=$1

  if [ -s "$1" ]; then
    cd $ulp/$path
  else
    cd $ulp
  fi
} # ulp

