# This is a list of file patterns that keeptmpclean will use to determine
# what file patterns should be removed from /tmp. Note that this file is
# re-evaluated each time keeptmpclean notices a new file created in /tmp
.*ksnip.*
.*Screenlet.py.log
.*vpndownloader
.+.tmp
\+~.*
adb.*.log
appInsights*
birdtry*
chrome_remote_desktop.*
chromoting.*
clipboardcache.*
cloudcode*
config-err.*
dbus-*
dock-replace.log
dropbox.*
evince-.*
grilo-plugin-cache*
hsperfdata_.*
instance_my_weather_indicator.lock
mozilla_.*
MozillaMailnews
node-compile-cache
nsemail*
orbit-.*
plugtmp
pms-.*
pulse-.*
qipc*
qt-trayicon.*
qt-trayicon.*
qtsingleapp-zoom*
r2-ipc
rainlendar2*
Rainlendar2*
remmina_log_file.log
scoped_*
screenlets
screenlets-daemon.py.log
snap.*
ssh-.*
SWT-*
systemd-.*
Temp-*
tmp+
tracker-*
ubuntu-advantage
userstorage.*
vboxdrv-Module*
vmware-root
VMwareDnD
xssv\..*
