#!/bin/bash
################################################################################
#
# File:         $RCSfile: set_colors,v $
# Revision:	$Revision: 1.3 $
# Description:  Set color variables
# Author:       Andrew@DeFaria.com
# Created:      Thu Jun  6 08:31:57 PDT 1996
# Modified:     $Date: 2010/04/12 15:57:33 $
# Language:     bash
#
# (c) Copyright 2000-2005, Andrew@DeFaria.com, all rights reserved.
#
################################################################################
esc=$(echo "\033")

if [ "$TERM" = "vt100" -o \
     "$TERM" = "vt220" ]; then
  NORMAL="$esc[0m"
  BOLD="$esc[1m"
  UNDERLINE="$esc[4m"
  BLINK="$esc[5m"
  INVERSE="$esc[7m"
elif [ "$TERM" = "dtterm" -o "$TERM" = "vt100" -o "$TERM" = "xterm" -o -z DTTERM ]; then
  NORMAL="$esc[39m"
  RED="$esc[31m"
  B_RED=$RED
  GREEN="$esc[32m"
  B_GREEN=$GREEN
  YELLOW="$esc[33m"
  B_YELLOW=$YELLOW
  BLUE="$esc[34m"
  B_BLUE=$BLUE
  MAGENTA="$esc[35m"
  B_MAGENTA=$MAGENTA
  AQUA="$esc[36m"
  B_AQUA=$AQUA
  WHITE="$esc[36m"
  B_WHITE=$WHITE
elif [ "$TERM" = "hp" -o "$TERM" = "hpterm" ]; then
  NORMAL="$esc&d@$esc&v0S"
  RED="$esc&v1S"
  GREEN="$esc&v2S"
  YELLOW="$esc&v3S"
  BLUE="$esc&v4S"
  PURPLE="$esc&v5S"
  AQUA="$esc&v6S"
  HB_NORMAL="$esc&v0S$esc&dK"
  B_NORMAL="$esc&v0S$esc&dB"
  HB_RED="$esc&v1S$esc&dK"
  B_RED="$esc&v1S$esc&dB"
  HB_GREEN="$esc&v2S$esc&dK"
  B_GREEN="$esc&v2S$esc&dB"
  HB_YELLOW="$esc&v3S$esc&dK"
  B_YELLOW="$esc&v3S$esc&dB"
  HB_BLUE="$esc&v4S$esc&dK"
  B_BLUE="$esc&v4S$esc&dB"
  PURPLE="$esc&v5S"
  HB_PURPLE="$esc&v5S$esc&dK"
  B_PURPLE="$esc&v5S$esc&dB"
  HB_AQUA="$esc&v6S$esc&dK"
  B_AQUA="$esc&v6S$esc&dB"
  INVERSE="$esc&v7S"
  HB_INVERSE="$esc&v7S$esc&dK"
  B_INVERSE="$esc&v7S$esc&dB"
fi
