set background=light
set autoindent
set autowrite
syntax enable
set nocompatible
set backspace=indent,eol,start
set hlsearch
set ff=unix
colorscheme quiet
map!  
set number
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif

