From: ASAP Adm <ASAPAdm@Ameriquest.net>
To: MMonterrey@Ameriquest.com, GSaha@Ameriquest.com, RRao@Amerquest.com, abhijit.bhide@tavant.com
Subject: $CLEARCASE_OP_KIND: $CLEARCASE_PN
--
This is a notification that a $CLEARCASE_OP_KIND has occurred:

Element:        $CLEARCASE_PN
Branch:         $CLEARCASE_BRTYPE
Operation:      $CLEARCASE_OP_KIND
User:           $CLEARCASE_USER
View:           $CLEARCASE_VIEW_TAG
Comments:       

$CLEARCASE_COMMENT

For information about recent activity see http://asapcm.ameriquest.net/logs
